import type { Metadata } from "next";
import localFont from "next/font/local";
import { ReactNode } from "react";
import { JSX } from "react/jsx-runtime";
import "./globals.css";

const pretendard = localFont({
  src: "../public/fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// TODO: production에 배포한 이후
// export const metadata: Metadata = {
//   metadataBase: new URL(url),
//   title: {
//     default: title,
//     template: `%s | ${title}`,
//   },
//   description: description,
//   alternates: {
//     canonical: "/",
//   },
//   openGraph: {
//     type: "website",
//     locale: "ko_KR",
//     url: url,
//     siteName: title,
//     title: title,
//     description: description,
//   },
//   twitter: {
//     card: "summary_large_image",
//     title: title,
//     description: description,
//   },
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): JSX.Element {
  return (
    <html lang="ko" className={`${pretendard.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col bg-background font-sans break-keep text-foreground">
        {children}
      </body>
    </html>
  );
}
